// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALIpuVaakfHcaBJOW77LFM5ucbN5PMaUM',
    appId: '1:540764827655:web:1a63204031cc8609cfbaa2',
    messagingSenderId: '540764827655',
    projectId: 'personalchatapp-65bd9',
    authDomain: 'personalchatapp-65bd9.firebaseapp.com',
    storageBucket: 'personalchatapp-65bd9.appspot.com',
    measurementId: 'G-91M60NZ6K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUko5wiWGfJ6l_6pesVX_ssvbx8Y4Xch8',
    appId: '1:540764827655:android:b8e38e0f51abb459cfbaa2',
    messagingSenderId: '540764827655',
    projectId: 'personalchatapp-65bd9',
    storageBucket: 'personalchatapp-65bd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALCHsZOYgrJQASe0Nz0RCjD96PpC8nrgI',
    appId: '1:540764827655:ios:4ce5b7d6669c57dbcfbaa2',
    messagingSenderId: '540764827655',
    projectId: 'personalchatapp-65bd9',
    storageBucket: 'personalchatapp-65bd9.appspot.com',
    iosBundleId: 'com.example.persoanlchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALCHsZOYgrJQASe0Nz0RCjD96PpC8nrgI',
    appId: '1:540764827655:ios:f761aede74b473b9cfbaa2',
    messagingSenderId: '540764827655',
    projectId: 'personalchatapp-65bd9',
    storageBucket: 'personalchatapp-65bd9.appspot.com',
    iosBundleId: 'com.example.persoanlchatapp.RunnerTests',
  );
}
